[package]
name = "voulr"
version = "0.2.8"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
inquire = "0.7.5"

[profile.release]
opt-level = 's' # optimize for size
lto = true
strip = true
