name: publish

on:
    push:
        tags:
            - "v*"

permissions:
    contents: read
    id-token: write

jobs:
    build:
        name: build ${{ matrix.target }}
        strategy:
            matrix:
                include:
                    - target: aarch64-apple-darwin
                      os: macos-latest
                    - target: x86_64-apple-darwin
                      os: macos-latest
                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
                    - target: x86_64-unknown-linux-musl
                      os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: build (cross)
              if: matrix.target == 'x86_64-unknown-linux-musl'
              run: |
                  cargo install cross
                  cross build --release --target ${{ matrix.target }}

            - name: build (native)
              if: matrix.target != 'x86_64-unknown-linux-musl'
              run: cargo build --release --target ${{ matrix.target }}

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.target }}
                  path: target/${{ matrix.target }}/release

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: compress
              run: |
                  cd artifacts
                  tar -czf voulr-aarch64-apple-darwin.tar.gz -C aarch64-apple-darwin voulr
                  tar -czf voulr-x86_64-apple-darwin.tar.gz -C x86_64-apple-darwin voulr
                  tar -czf voulr-x86_64-pc-windows-msvc.tar.gz -C x86_64-pc-windows-msvc voulr.exe
                  tar -czf voulr-x86_64-unknown-linux-musl.tar.gz -C x86_64-unknown-linux-musl voulr

            - name: release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  files: artifacts/*.tar.gz
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"
                  provenance: true

            - name: publish to npm
              run: cd npm && npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
