name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        name: build ${{ matrix.platform }}
        strategy:
            matrix:
                include:
                    - platform: macos (silicon)
                      os: macos-latest
                      target: aarch64-apple-darwin
                      cross: false

                    - platform: macos (intel)
                      os: macos-latest
                      target: x86_64-apple-darwin
                      cross: false

                    - platform: windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      cross: false

                    - platform: linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      cross: true

        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: install cross
              if: matrix.cross
              run: cargo install cross

            - name: build
              shell: bash
              run: |
                  if ${{ matrix.cross }}; then
                    cross build --release --target ${{ matrix.target }}
                  else  
                    cargo build --release --target ${{ matrix.target }}
                  fi

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: copy artifacts
              run: |
                  mkdir artifacts
                  mv target/aarch64-apple-darwin/release/voulr pkg/bin/voulr-macos-silicon
                  mv target/x86_64-apple-darwin/release/voulr pkg/bin/voulr-macos-intel
                  mv target/x86_64-pc-windows-msvc/release/voulr.exe pkg/bin/voulr-windows.exe
                  mv target/x86_64-unknown-linux-musl/release/voulr pkg/bin/voulr-linux

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: publish to npm
              run: cd pkg && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
