name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        strategy:
            matrix:
                include:
                    - target: x86_64-unknown-linux-musl
                      os: ubuntu-latest
                      binary: voulr-linux
                    - target: x86_64-pc-windows-gnu
                      os: ubuntu-latest
                      binary: voulr-win64.exe
                    - target: i686-pc-windows-gnu
                      os: ubuntu-latest
                      binary: voulr-win32.exe
                    - target: x86_64-apple-darwin
                      os: macos-latest
                      binary: voulr-macos
                    - target: aarch64-apple-darwin
                      os: macos-latest
                      binary: voulr-macos-arm64
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Install cross (Ubuntu only)
              if: runner.os == 'Linux'
              run: cargo install cross

            - name: Build (Ubuntu)
              if: runner.os == 'Linux'
              run: cross build --release --target ${{ matrix.target }}

            - name: Build (MacOS)
              if: runner.os == 'macOS'
              run: cargo build --release --target ${{ matrix.target }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.binary }}
                  path: target/${{ matrix.target }}/release/${{ matrix.binary }}

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  path: pkg/bin

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: Publish to npm
              run: cd pkg && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
