name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt
                  targets: x86_64-unknown-linux-musl,x86_64-pc-windows-gnu,i686-pc-windows-gnu,x86_64-apple-darwin,aarch64-apple-darwin

            - name: install cross
              run: cargo install cross

            - name: build
              run: |
                  cross build --release --target x86_64-unknown-linux-musl
                  cross build --release --target x86_64-pc-windows-gnu
                  cross build --release --target i686-pc-windows-gnu
                  cross build --release --target x86_64-apple-darwin
                  cross build --release --target aarch64-apple-darwin

            - name: copy artifacts
              run: |
                  mkdir -p pkg/bin
                  mv target/x86_64-unknown-linux-musl/release/voulr pkg/bin/voulr-linux
                  mv target/x86_64-pc-windows-gnu/release/voulr.exe pkg/bin/voulr-win64.exe
                  mv target/i686-pc-windows-gnu/release/voulr.exe pkg/bin/voulr-win32.exe
                  mv target/x86_64-apple-darwin/release/voulr pkg/bin/voulr-macos
                  mv target/aarch64-apple-darwin/release/voulr pkg/bin/voulr-macos-arm64

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: publish to npm
              run: cd pkg && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
