name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        name: build ${{ matrix.platform }}
        strategy:
            matrix:
                include:
                    - platform: macos (silicon)
                      os: macos-latest
                      target: aarch64-apple-darwin
                      cross: false

                    - platform: macos (intel)
                      os: macos-latest
                      target: x86_64-apple-darwin
                      cross: false

                    - platform: windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      cross: false

                    - platform: linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      cross: true

        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: install cross
              if: matrix.cross
              run: cargo install cross

            - name: build
              shell: bash
              run: |
                  if ${{ matrix.cross }}; then
                    cross build --release --target ${{ matrix.target }}
                  else  
                    cargo build --release --target ${{ matrix.target }}
                  fi

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.target }}
                  path: target/${{ matrix.target }}/release

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts

            - name: compress
              run: |
                  mkdir -p compressed
                  tar -czvf compressed/voulr-macos-silicon.tar.gz artifacts/aarch64-apple-darwin/voulr
                  tar -czvf compressed/voulr-macos-intel.tar.gz artifacts/x86_64-apple-darwin/voulr
                  tar -czvf compressed/voulr-windows.tar.gz artifacts/x86_64-pc-windows-msvc/voulr.exe
                  tar -czvf compressed/voulr-linux.tar.gz artifacts/x86_64-unknown-linux-musl/voulr

            - name: get version
              id: get_version
              run: echo "version=$(grep "version" Cargo.toml | head -n1 | cut -d '"' -f2)" >> $GITHUB_OUTPUT

            - name: release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.get_version.outputs.version }}
                  files: compressed/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: publish to npm
              run: |
                  cd pkg
                  cp ../README.md .
                  jq '.version = "${{ steps.get_version.outputs.version }}"' package.json > tmp && mv tmp package.json
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
