name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        name: build ${{ matrix.platform }}
        strategy:
            matrix:
                include:
                    - platform: macos (apple silicon)
                      os: macos-latest
                      target: aarch64-apple-darwin
                      cross: false

                    - platform: macos (intel)
                      os: macos-latest
                      target: x86_64-apple-darwin
                      cross: false

                    - platform: windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      cross: false

                    - platform: linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      cross: true

        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: install cross
              if: matrix.cross
              run: cargo install cross

            - name: build
              run: |
                  if ${{ matrix.cross }}; then
                    cross build --release --target ${{ matrix.target }}
                  else  
                    cargo build --release --target ${{ matrix.target }}
                  fi

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                  path: target/${{ matrix.target }}/release/voulr*

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                  path: pkg/bin

            - name: install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: publish to npm
              run: cd pkg && npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
