name: publish
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: aarch64-apple-darwin,x86_64-apple-darwin,x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc

            - name: build
              run: |
                  cargo build --release --target aarch64-apple-darwin
                  cargo build --release --target x86_64-apple-darwin
                  cargo build --release --target x86_64-unknown-linux-gnu
                  cargo build --release --target x86_64-pc-windows-msvc

            - name: copy artifacts
              run: |
                  mkdir -p pkg/bin
                  cp target/aarch64-apple-darwin/release/voulr pkg/bin/voulr-darwin-arm64
                  cp target/x86_64-apple-darwin/release/voulr pkg/bin/voulr-darwin-x64
                  cp target/x86_64-unknown-linux-gnu/release/voulr pkg/bin/voulr-linux-x64
                  cp target/x86_64-pc-windows-msvc/release/voulr.exe pkg/bin/voulr-win-x64.exe

            - name: install node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: publish to npm
              run: |
                  cd pkg
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
